---
- hosts: main
  tasks:
    - name: Create a file
      file: path=/tmp/testing.txt state=touch
    - copy:
        src: hello_world.txt
        dest: /tmp/hello_world.txt
- hosts: localhost
  tasks:
    - name: Install libreoffice
      apt:
        name: libreoffice
        update_cache: yes
      become: true

- hosts: dev_machines
  tasks:
    - name: Add bluefish repo
      apt_repository:
        repo: deb http://ftp.se.debian.org/debian jessie main
        state: present
      become: true
    - name: Install bluefish
      apt:
        name: bluefish
      become: true
# rpeo
#http://ftp.se.debian.org/debian jessie main 
#    - name: Add repository
 #     apt_repository:
  #      repo: deb add-apt-repository ppa:openjdk-r/ppa
   #     state: present
    #  become: true
    #- name: Install opendjk7
     # apt:
     #   name: openjdk-7-jdk:amd64
      #  update_cache: yes
       # state: build-dep
#      become: true
 #   - name: Install dropbox
#      command: ' wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -'
  #    become: true
#
#    - name: Install dropbox
#      shell: 'cd ~ && wget -O - "https://www.dropbox.com/download/?plat=lnx.x86_64" | tar xzf -'
